Use wrap_parameters in pipelines controller
This makes it possible to workaround a bug in `safe_constantize` which
caused a `LoadError` exception when doing

```
"Pipeline".safe_constantize
LoadError: Unable to autoload constant Pipeline, expected
/home/grzesiek/gdk/gitlab/app/models/ci/pipeline.rb to define it
```

See https://github.com/rails/rails/issues/28854 for more details.